export const SET_ROUNDS = 'SET_ROUNDS';
export const SET_FIGHTER_ONE_NAME = 'SET_FIGHTER_ONE_NAME';
export const SET_FIGHTER_TWO_NAME = 'SET_FIGHTER_TWO_NAME';
export const SET_FIGHTER_ONE_ROUND_SCORE = 'SET_FIGHTER_ONE_ROUND_SCORE';
export const SET_FIGHTER_TWO_ROUND_SCORE = 'SET_FIGHTER_TWO_ROUND_SCORE';